name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk with Gradle
      run: ./gradlew assembleRelease && find . -name "*.apk"
    - uses: Tlaster/android-sign@v1
      name: Sign apk
      with:
        releaseDirectory: |
          app/build/outputs/apk/release
          app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        output: build/release/signed
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: busybox-unsigned.apk
        path: app/build/outputs/apk/release
